<a href="https://colab.research.google.com/github/GazalaSayyad/zoo/blob/master/DT_Zoo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Decision Tree

In [0]:
import pandas as pd
import numpy as np
from sklearn.tree import export_graphviz
from sklearn.model_selection import train_test_split

In [0]:
#Import all columns omitting the fist which consists the names of the animals
dataset = pd.read_csv('Zoo_New.csv',
                      names=['animal_name','hair','feathers','eggs','milk',
                                                   'airbone','aquatic','predator','toothed','backbone',
                                                  'breathes','venomous','fins','legs','tail','domestic','catsize','class',])
#We don't use animal name for classification because it is just a string stating the 
#name and it won't provide any extra information for classification in this context
dataset=dataset.drop('animal_name',axis=1)

In [3]:
dataset.head()

hair  feathers  eggs  milk  airbone  ...  legs  tail  domestic  catsize  class
0     1         0     0     1        0  ...     4     0         0        1      1
1     1         0     0     1        0  ...     4     1         0        1      1
2     0         0     1     0        0  ...     0     1         0        0      4
3     1         0     0     1        0  ...     4     0         0        1      1
4     1         0     0     1        0  ...     4     1         0        1      1

[5 rows x 17 columns]

In [5]:
dataset.tail()

hair  feathers  eggs  milk  airbone  ...  legs  tail  domestic  catsize  class
96      1         0     0     1        0  ...     2     1         0        1      1
97      1         0     1     0        1  ...     6     0         0        0      6
98      1         0     0     1        0  ...     4     1         0        1      1
99      0         0     1     0        0  ...     0     0         0        0      7
100     0         1     1     0        1  ...     2     1         0        0      2

[5 rows x 17 columns]

In [6]:
np.unique(dataset['class'].values)

array([1, 2, 3, 4, 5, 6, 7])

In [0]:
training_data, testing_data = train_test_split(dataset,test_size=0.2)

In [8]:
training_data = training_data.values
print(training_data)

[[0 0 1 ... 0 0 5]
 [1 0 0 ... 1 1 1]
 [1 0 0 ... 1 1 1]
 ...
 [0 1 1 ... 0 1 2]
 [1 0 0 ... 0 0 1]
 [0 0 1 ... 0 0 4]]


In [9]:
testing_data = testing_data.values
print(testing_data )

[[1 0 0 1 0 1 1 1 1 1 0 1 2 1 0 1 1]
 [1 0 1 0 1 0 0 0 0 1 1 0 6 0 0 0 6]
 [0 0 1 0 0 1 1 1 1 0 0 1 0 1 0 1 4]
 [0 1 1 0 1 1 1 0 1 1 0 0 2 1 0 0 2]
 [0 0 1 0 0 1 1 1 1 1 1 0 4 0 0 0 5]
 [0 1 1 0 0 0 1 0 1 1 0 0 2 1 0 0 2]
 [1 0 0 1 0 0 0 1 1 1 0 0 2 1 0 1 1]
 [0 0 1 0 0 1 1 1 1 1 0 0 4 0 0 0 5]
 [0 0 1 0 0 1 1 1 1 0 0 1 0 1 0 0 4]
 [0 1 1 0 1 0 1 0 1 1 0 0 2 1 0 0 2]
 [1 0 0 1 0 0 1 1 1 1 0 0 4 1 0 1 1]
 [0 0 1 0 0 1 1 1 1 0 0 1 0 1 0 1 4]
 [0 0 1 0 0 0 1 1 1 1 0 0 0 1 0 0 3]
 [1 0 0 1 0 0 0 1 1 1 0 0 4 1 0 1 1]
 [0 0 0 1 0 1 1 1 1 1 0 1 0 1 0 1 1]
 [0 0 1 0 0 1 1 0 0 0 0 0 4 0 0 0 7]
 [1 0 0 1 0 0 1 1 1 1 0 0 4 1 0 0 1]
 [1 0 0 1 0 1 1 1 1 1 0 0 4 1 0 1 1]
 [1 0 0 1 0 0 1 1 1 1 0 0 4 1 0 1 1]
 [0 0 1 0 1 0 1 0 0 1 0 0 6 0 0 0 6]
 [1 0 0 1 0 0 0 1 1 1 0 0 4 1 0 0 1]]


In [0]:
from sklearn import tree

In [0]:
clf = tree.DecisionTreeClassifier(criterion='entropy')

In [13]:
clf

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='entropy',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [0]:
# Fitting the data
clf = clf.fit(training_data[:,:16],training_data[:,16])

In [0]:
# Calculating the labels for test data
pred = clf.predict(testing_data[:,:16])

In [0]:
# Importing library to calculate accuracy score
from sklearn.metrics import accuracy_score

In [17]:
# Calculating accuracy
accuracy_score(testing_data[:,16], pred)

0.9523809523809523