<a href="https://colab.research.google.com/github/GazalaSayyad/zoo/blob/master/Knn_zoo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn import linear_model

In [0]:
dataset = pd.read_csv('zoo.csv')

In [0]:
dataset.head()


animal_name  hair  feathers  eggs  ...  tail  domestic  catsize  class_type
0    aardvark     1         0     0  ...     0         0        1           1
1    antelope     1         0     0  ...     1         0        1           1
2        bass     0         0     1  ...     1         0        0           4
3        bear     1         0     0  ...     0         0        1           1
4        boar     1         0     0  ...     1         0        1           1

[5 rows x 18 columns]

In [0]:
dataset.shape

(101, 18)

In [0]:
dataset=dataset.drop('animal_name',axis=1)

In [0]:
training_data, testing_data = train_test_split(dataset,test_size=0.2)

In [14]:
training_data = training_data.values
print(training_data)

[[0 1 1 ... 1 0 2]
 [1 0 0 ... 0 1 1]
 [0 0 1 ... 0 0 4]
 ...
 [0 1 1 ... 0 0 2]
 [0 0 1 ... 0 0 7]
 [0 0 1 ... 1 0 4]]


In [15]:
testing_data = testing_data.values
print(testing_data )

[[0 0 1 0 0 1 1 0 0 0 0 0 5 0 0 0 7]
 [1 0 0 1 0 0 0 1 1 1 0 0 4 1 0 1 1]
 [0 1 1 0 1 0 1 0 1 1 0 0 2 1 0 0 2]
 [1 0 0 1 0 0 0 1 1 1 0 0 4 1 1 1 1]
 [0 0 1 0 0 1 1 1 1 0 0 1 0 1 0 1 4]
 [1 0 0 1 0 1 1 1 1 1 0 0 4 1 0 1 1]
 [1 0 0 1 0 0 1 1 1 1 0 0 4 1 0 1 1]
 [0 0 0 1 0 1 1 1 1 1 0 1 0 1 0 1 1]
 [0 1 1 0 1 0 0 0 1 1 0 0 2 1 0 0 2]
 [0 0 1 0 0 1 1 1 1 0 0 1 0 1 0 0 4]
 [0 0 1 0 0 0 1 1 1 1 1 0 0 1 0 0 3]
 [1 0 0 1 0 0 1 1 1 1 0 0 4 1 0 1 1]
 [0 1 1 0 1 0 1 0 1 1 0 0 2 1 0 0 2]
 [0 1 1 0 0 1 1 0 1 1 0 0 2 1 0 1 2]
 [0 1 1 0 1 1 1 0 1 1 0 0 2 1 0 0 2]
 [1 0 0 1 0 0 0 1 1 1 0 0 4 1 0 1 1]
 [0 0 1 0 0 1 1 0 0 0 0 0 8 0 0 1 7]
 [1 0 0 1 0 0 0 1 1 1 0 0 4 1 1 1 1]
 [0 0 1 0 0 1 1 1 1 0 0 1 0 1 0 1 4]
 [1 0 0 1 1 0 0 1 1 1 0 0 2 1 0 0 1]
 [1 0 0 1 0 0 0 1 1 1 0 0 4 1 0 1 1]]


In [0]:
from sklearn.neighbors import KNeighborsClassifier

In [0]:
k = 3
neigh = KNeighborsClassifier(n_neighbors=k)
neigh = KNeighborsClassifier(n_neighbors=k,metric="euclidean", algorithm="brute")

In [18]:
training_data = dataset.values
neigh.fit (training_data[:,:16],training_data[:,16])

KNeighborsClassifier(algorithm='brute', leaf_size=30, metric='euclidean',
                     metric_params=None, n_jobs=None, n_neighbors=3, p=2,
                     weights='uniform')

In [0]:
from sklearn.metrics import accuracy_score

In [24]:
accuracy_score(testing_data[:,16], pred)

1.0